DROP TABLE ALGORITHM CASCADE CONSTRAINTS;
DROP TABLE FEATURE_VECTOR CASCADE CONSTRAINTS;
DROP TABLE IMAGES_TABLE CASCADE CONSTRAINTS;
DROP TABLE IMAGE_FEATURES CASCADE CONSTRAINTS;
DROP TABLE STATS CASCADE CONSTRAINTS;

CREATE TABLE ALGORITHM
  ( ID INTEGER NOT NULL , NAME VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ALGORITHM ADD CONSTRAINT ALGORITHM_PK PRIMARY KEY ( ID ) ;


CREATE TABLE FEATURE_VECTOR
  (
    ID           INTEGER NOT NULL ,
    PATH         VARCHAR2 (1024) NOT NULL ,
    ALGORITHM_ID INTEGER NOT NULL
  ) ;
ALTER TABLE FEATURE_VECTOR ADD CONSTRAINT FEATURE_VECTOR_PK PRIMARY KEY ( ID ) ;


CREATE TABLE IMAGES_TABLE
  (
    ID   INTEGER NOT NULL ,
    LINK VARCHAR2 (1024) NOT NULL
  ) ;
ALTER TABLE IMAGES_TABLE ADD CONSTRAINT IMAGES_TABLE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE IMAGE_FEATURES
  (
    IMAGE_ID   INTEGER NOT NULL ,
    FEATURE_ID INTEGER NOT NULL
  ) ;


CREATE TABLE STATS
  (
    MAX_DB_SIZE     INTEGER NOT NULL ,
    CURRENT_DB_SIZE INTEGER NOT NULL
  ) ;


ALTER TABLE FEATURE_VECTOR ADD CONSTRAINT FEATURE_VECTOR_ALGORITHM_FK FOREIGN KEY ( ALGORITHM_ID ) REFERENCES ALGORITHM ( ID ) ;

ALTER TABLE IMAGE_FEATURES ADD CONSTRAINT IMAGE_FEATURES_FEA_VECT_FK FOREIGN KEY ( FEATURE_ID ) REFERENCES FEATURE_VECTOR ( ID ) ;

ALTER TABLE IMAGE_FEATURES ADD CONSTRAINT IMAGE_FEATURES_IMAGES_TABLE_FK FOREIGN KEY ( IMAGE_ID ) REFERENCES IMAGES_TABLE ( ID ) ;
