DROP TABLE ALGORITHM_SLAVE CASCADE CONSTRAINTS;
DROP TABLE FEATURE_VECTOR_SLAVE CASCADE CONSTRAINTS;
DROP TABLE IMAGES_TABLE_SLAVE CASCADE CONSTRAINTS;
DROP TABLE IMAGE_FEATURES_SLAVE CASCADE CONSTRAINTS;
DROP TABLE STATS_SLAVE CASCADE CONSTRAINTS;


CREATE TABLE ALGORITHM_SLAVE
  (
  ID INTEGER NOT NULL , NAME VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ALGORITHM_SLAVE ADD CONSTRAINT ALGORITHM_PK_SLAVE PRIMARY KEY ( ID ) ;


CREATE TABLE FEATURE_VECTOR_SLAVE
  (
    ID           INTEGER NOT NULL ,
    PATH         VARCHAR2 (1024) NOT NULL ,
    ALGORITHM_ID INTEGER NOT NULL
  ) ;
ALTER TABLE FEATURE_VECTOR_SLAVE ADD CONSTRAINT FEATURE_VECTOR_PK_SLAVE PRIMARY KEY ( ID ) ;


CREATE TABLE IMAGES_TABLE_SLAVE
  (
    ID   INTEGER NOT NULL ,
    LINK VARCHAR2 (1024) NOT NULL
  ) ;
ALTER TABLE IMAGES_TABLE_SLAVE ADD CONSTRAINT IMAGES_TABLE_PK_SLAVE PRIMARY KEY ( ID ) ;


CREATE TABLE IMAGE_FEATURES_SLAVE
  (
    IMAGE_ID   INTEGER NOT NULL ,
    FEATURE_ID INTEGER NOT NULL
  ) ;


CREATE TABLE STATS_SLAVE
  (
    MAX_DB_SIZE     INTEGER NOT NULL ,
    CURRENT_DB_SIZE INTEGER NOT NULL
  ) ;


ALTER TABLE FEATURE_VECTOR_SLAVE ADD CONSTRAINT FEAT_ALGORITHM_FK_SLAVE FOREIGN KEY ( ALGORITHM_ID ) REFERENCES ALGORITHM_SLAVE ( ID ) ;

ALTER TABLE IMAGE_FEATURES_SLAVE ADD CONSTRAINT IMAGE_FEAT_FEAT_FK_SLAVE FOREIGN KEY ( FEATURE_ID ) REFERENCES FEATURE_VECTOR_SLAVE ( ID ) ;

ALTER TABLE IMAGE_FEATURES_SLAVE ADD CONSTRAINT IMAGE_FEAT_IMAG_FK_SLAVE FOREIGN KEY ( IMAGE_ID ) REFERENCES IMAGES_TABLE_SLAVE ( ID ) ;


--------------------------------------------------------------------------------
-- TRIGGERS --------------------------------------------------------------------
--------------------------------------------------------------------------------
DROP SEQUENCE FEATURE_VECTOR_SEQ_SLAVE; 
CREATE SEQUENCE FEATURE_VECTOR_SEQ_SLAVE START WITH 1;
/
CREATE OR REPLACE TRIGGER FEATURE_VECTOR_TRIGGER_SLAVE
BEFORE INSERT ON FEATURE_VECTOR_SLAVE
FOR EACH ROW
BEGIN
  SELECT FEATURE_VECTOR_SEQ_SLAVE.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

DROP SEQUENCE ALGORITHM_SEQ_SLAVE; 
CREATE SEQUENCE ALGORITHM_SEQ_SLAVE START WITH 1;
/
CREATE OR REPLACE TRIGGER ALGORITHM_ID_TRIGGER_SLAVE
BEFORE INSERT ON ALGORITHM_SLAVE
FOR EACH ROW
BEGIN
  SELECT ALGORITHM_SEQ_SLAVE.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

DROP SEQUENCE IMAGES_TABLE_SEQ_SLAVE; 
CREATE SEQUENCE IMAGES_TABLE_SEQ_SLAVE START WITH 1;
/
CREATE OR REPLACE TRIGGER IMAGES_TABLE_TRIGGER_SLAVE
BEFORE INSERT ON IMAGES_TABLE_SLAVE 
FOR EACH ROW
BEGIN
  SELECT IMAGES_TABLE_SEQ_SLAVE.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
commit;

